disabled_rules: # rule identifiers to exclude from running
    - line_length
    - fallthrough
opt_in_rules: # some rules are only opt-in
    - closure_end_indentation
    - closure_spacing
    - conditional_returns_on_newline
    - fatal_error_message
    - joined_default_parameter
    - let_var_whitespace
    - literal_expression_end_indentation
    - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - private_action
    - prohibited_super_call
    - redundant_nil_coalescing
    - sorted_first_last
    - sorted_imports
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - yoda_condition
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - Source/ExcludedFolder
    - Source/ExcludedFile.swift

identifier_name:
    excluded:
    - id

